---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack
spec:
  replicas: 1
  server:
    containerSpec:
      name: llama-stack
      port: 8321
      env:
      # - name: LLAMA_3_2_3B_API_TOKEN
      #   valueFrom:
      #     secretKeyRef:
      #       name: llama-3-2-3b
      #       key: apiKey
      # No API tokens needed for local vLLM deployment
      # - name: TAVILY_API_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: tavily-search-key
      #       key: tavily-search-api-key
    distribution:
      #name: remote-vllm
      image: quay.io/eformat/distribution-remote-vllm:0.2.15
    userConfig:
      configMapName: llama-stack-config
